/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tenants */
        get: operations["list_tenants_tenants_get"];
        put?: never;
        /** Create Tenant */
        post: operations["create_tenant_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tenant */
        get: operations["get_tenant_tenants__tenant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Tenant */
        patch: operations["update_tenant_tenants__tenant_id__patch"];
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings__settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_settings_patch"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_users__user_id__patch"];
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_watchlist_get"];
        put?: never;
        /** Add Hotel */
        post: operations["add_hotel_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{hotel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_watchlist__hotel_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_watchlist__hotel_id__patch"];
        trace?: never;
    };
    "/watchlist/scan-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Now
         * @description Quét ngay toàn bộ watchlist của tenant (không đợi mốc giờ), ví dụ sau khi thêm khách sạn.
         */
        post: operations["scan_now_watchlist_scan_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/{hotel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hotel Detail */
        get: operations["hotel_detail_hotels__hotel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hotels/{hotel_id}/dates/{stay_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Day Detail */
        get: operations["day_detail_hotels__hotel_id__dates__stay_date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Insights */
        get: operations["list_insights_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/{insight_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Insight */
        get: operations["get_insight_insights__insight_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Insight
         * @description Tạo bản tin theo yêu cầu: ghi một dòng `pending` rồi đẩy job; dashboard poll trạng thái.
         */
        post: operations["generate_insight_insights_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pms/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template */
        get: operations["template_pms_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pms/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mapping */
        get: operations["get_mapping_pms_mapping_get"];
        /** Put Mapping */
        put: operations["put_mapping_pms_mapping_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pms/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_pms_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pms/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import File */
        post: operations["import_file_pms_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pms/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imports */
        get: operations["list_imports_pms_imports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pms/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Own Daily */
        get: operations["own_daily_pms_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_health_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_health_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sessions */
        get: operations["sessions_health_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/scan-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Now All
         * @description Operator: quét ngay mọi tenant đang hoạt động.
         */
        post: operations["scan_now_all_health_scan_now_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_file_pms_import_post */
        Body_import_file_pms_import_post: {
            /** File */
            file: string;
            /** Hotel Id */
            hotel_id: number;
            /**
             * Adapter
             * @default csv
             */
            adapter: string;
        };
        /** Body_preview_pms_preview_post */
        Body_preview_pms_preview_post: {
            /** File */
            file: string;
            /**
             * Adapter
             * @default csv
             */
            adapter: string;
        };
        /** CompsetDayOut */
        CompsetDayOut: {
            /**
             * Stay Date
             * Format: date
             */
            stay_date: string;
            /** Competitors Observed */
            competitors_observed: number;
            /** Competitors Sold Out */
            competitors_sold_out: number;
            /** Sold Out Share */
            sold_out_share: string | null;
            /** Min Price */
            min_price: string | null;
            /** Median Price */
            median_price: string | null;
            /** Currency */
            currency: string | null;
            /** Own Min Price */
            own_min_price: string | null;
            /** Own Status */
            own_status: string | null;
            /** Own Occupancy Pct */
            own_occupancy_pct: string | null;
            /** Own Rooms Available */
            own_rooms_available: number | null;
            /** Price Index */
            price_index: string | null;
        };
        /** DateCell */
        DateCell: {
            /**
             * Stay Date
             * Format: date
             */
            stay_date: string;
            /** Availability Status */
            availability_status: string | null;
            /** Exact Rooms Left */
            exact_rooms_left: number | null;
            /** Min Price */
            min_price: string | null;
            /** Currency */
            currency: string | null;
            /** Pickup 24H */
            pickup_24h: number | null;
            /** Velocity 3D */
            velocity_3d: string | null;
            /** Price Change 7D Pct */
            price_change_7d_pct: string | null;
            /** Exact Share */
            exact_share: string | null;
            /** Sold Out At */
            sold_out_at: string | null;
            /** Restocked At */
            restocked_at: string | null;
            /** Last Observed At */
            last_observed_at: string | null;
            /** Days To Arrival */
            days_to_arrival: number | null;
        };
        /** DayDetailOut */
        DayDetailOut: {
            hotel: components["schemas"]["HotelOut"];
            /**
             * Stay Date
             * Format: date
             */
            stay_date: string;
            /** Room Types */
            room_types: components["schemas"]["RoomTypeOut"][];
            /** Latest */
            latest: components["schemas"]["RoomSnapshotOut"][];
            /** History */
            history: components["schemas"]["RoomSnapshotOut"][];
            /** Observations */
            observations: components["schemas"]["HotelDateSnapshotOut"][];
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Hotel Id */
            hotel_id: number;
            /** Hotel Name */
            hotel_name: string | null;
            /** Hotel Slug */
            hotel_slug: string;
            /** Room Type Id */
            room_type_id: number | null;
            /** Room Type Name */
            room_type_name: string | null;
            /**
             * Stay Date
             * Format: date
             */
            stay_date: string;
            /** Event Type */
            event_type: string;
            /** From Value */
            from_value: string | null;
            /** To Value */
            to_value: string | null;
            /** Delta */
            delta: string | null;
            /** Confidence */
            confidence: string;
            /** Previous Scan Run Id */
            previous_scan_run_id: number | null;
            /** Scan Run Id */
            scan_run_id: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthSummaryOut */
        HealthSummaryOut: {
            /** Probes 15M */
            probes_15m: number;
            /** Blocked 15M */
            blocked_15m: number;
            /** Block Rate 15M */
            block_rate_15m: number;
            last_run: components["schemas"]["ScanRunOut"] | null;
            /** Active Sessions */
            active_sessions: number;
            /** Pending Analytics Runs */
            pending_analytics_runs: number[];
            /** Grafana Url */
            grafana_url: string | null;
        };
        /** HotelDateSnapshotOut */
        HotelDateSnapshotOut: {
            /** Scan Run Id */
            scan_run_id: number;
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Status */
            status: string;
            /** Exact Rooms Left */
            exact_rooms_left: number | null;
            /** Room Types Available */
            room_types_available: number;
            /** Room Types Sold Out */
            room_types_sold_out: number;
            /** Min Price */
            min_price: string | null;
            /** Currency */
            currency: string | null;
        };
        /** HotelDetailOut */
        HotelDetailOut: {
            hotel: components["schemas"]["HotelOut"];
            /** Role */
            role: string;
            /** Label */
            label: string | null;
            /** Metrics */
            metrics: components["schemas"]["DateCell"][];
            /** Events */
            events: components["schemas"]["EventOut"][];
        };
        /** HotelOut */
        HotelOut: {
            /** Id */
            id: number;
            /** Booking Url */
            booking_url: string;
            /** Booking Slug */
            booking_slug: string;
            /** Booking Hotel Id */
            booking_hotel_id: string | null;
            /** Name */
            name: string | null;
            /** City */
            city: string | null;
            /** Country Code */
            country_code: string;
            /** Star Rating */
            star_rating: string | null;
        };
        /** HotelRow */
        HotelRow: {
            hotel: components["schemas"]["HotelOut"];
            /** Role */
            role: string;
            /** Label */
            label: string | null;
            /** Cells */
            cells: components["schemas"]["DateCell"][];
        };
        /** InsightDetailOut */
        InsightDetailOut: {
            /** Id */
            id: number;
            /** Tenant Id */
            tenant_id: number;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Trigger */
            trigger: string;
            /** Status */
            status: string;
            /** Scan Run Id */
            scan_run_id: number | null;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Output Json */
            output_json: {
                [key: string]: unknown;
            } | null;
            /** Dropped Highlights */
            dropped_highlights: {
                [key: string]: unknown;
            }[];
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Cost Usd */
            cost_usd: string;
            /** Error */
            error: string | null;
            /** Input Json */
            input_json: {
                [key: string]: unknown;
            };
        };
        /** InsightOut */
        InsightOut: {
            /** Id */
            id: number;
            /** Tenant Id */
            tenant_id: number;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Trigger */
            trigger: string;
            /** Status */
            status: string;
            /** Scan Run Id */
            scan_run_id: number | null;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Output Json */
            output_json: {
                [key: string]: unknown;
            } | null;
            /** Dropped Highlights */
            dropped_highlights: {
                [key: string]: unknown;
            }[];
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Cost Usd */
            cost_usd: string;
            /** Error */
            error: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MappingIn */
        MappingIn: {
            /**
             * Adapter
             * @default csv
             */
            adapter: string;
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
        };
        /** MappingOut */
        MappingOut: {
            /** Adapter */
            adapter: string;
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
            /** Canonical Columns */
            canonical_columns: string[];
        };
        /** OverviewOut */
        OverviewOut: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Hotels */
            hotels: components["schemas"]["HotelRow"][];
            /** Compset */
            compset: components["schemas"]["CompsetDayOut"][];
            last_run: components["schemas"]["ScanRunOut"] | null;
        };
        /** OwnDailyOut */
        OwnDailyOut: {
            /** Hotel Id */
            hotel_id: number;
            /** Stay Date */
            stay_date: string | unknown;
            /** Rooms Total */
            rooms_total: number | null;
            /** Rooms Sold */
            rooms_sold: number | null;
            /** Rooms Available */
            rooms_available: number | null;
            /** Occupancy Pct */
            occupancy_pct: unknown;
            /** Adr */
            adr: unknown;
            /** Revenue */
            revenue: unknown;
            /** Source */
            source: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
        };
        /** PmsImportOut */
        PmsImportOut: {
            /** Id */
            id: number;
            /** Tenant Id */
            tenant_id: number;
            /** Hotel Id */
            hotel_id: number | null;
            /** Filename */
            filename: string;
            /** Adapter */
            adapter: string;
            /** Row Count */
            row_count: number;
            /** Ok Count */
            ok_count: number;
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Columns */
            columns: string[];
            /** Sample */
            sample: {
                [key: string]: unknown;
            }[];
            /** Suggested Mapping */
            suggested_mapping: {
                [key: string]: string;
            };
            /** Parsed Ok */
            parsed_ok: number;
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
        };
        /** RoomSnapshotOut */
        RoomSnapshotOut: {
            /** Id */
            id: number;
            /** Room Type Id */
            room_type_id: number;
            /**
             * Stay Date
             * Format: date
             */
            stay_date: string;
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            /** Rooms Left */
            rooms_left: number | null;
            /** Stock Confidence */
            stock_confidence: string;
            /** Badge Count */
            badge_count: number | null;
            /** Dropdown Max */
            dropdown_max: number | null;
            /** Min Price */
            min_price: string | null;
            /** Min Refundable Price */
            min_refundable_price: string | null;
            /** Currency */
            currency: string | null;
            /** Rates */
            rates: {
                [key: string]: unknown;
            }[];
        };
        /** RoomTypeOut */
        RoomTypeOut: {
            /** Id */
            id: number;
            /** Booking Room Id */
            booking_room_id: string;
            /** Name */
            name: string;
            /** Max Occupancy */
            max_occupancy: number | null;
        };
        /** ScanRunOut */
        ScanRunOut: {
            /** Id */
            id: number;
            /** Trigger Key */
            trigger_key: string;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Total Jobs */
            total_jobs: number;
            /** Total Probes */
            total_probes: number;
            /** Ok Count */
            ok_count: number;
            /** Sold Out Count */
            sold_out_count: number;
            /** Blocked Count */
            blocked_count: number;
            /** Error Count */
            error_count: number;
        };
        /** ScrapeSessionOut */
        ScrapeSessionOut: {
            /** Id */
            id: string;
            /** Worker Id */
            worker_id: string;
            /** Proxy Id */
            proxy_id: string;
            /** Proxy Country */
            proxy_country: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Retired At */
            retired_at: string | null;
            /** Request Count */
            request_count: number;
            /** Block Count */
            block_count: number;
            /** Status */
            status: string;
        };
        /** TenantCreate */
        TenantCreate: {
            /** Name */
            name: string;
            /**
             * Timezone
             * @default Asia/Ho_Chi_Minh
             */
            timezone: string;
            /**
             * Scan Times
             * @default [
             *       "06:00",
             *       "14:00",
             *       "22:00"
             *     ]
             */
            scan_times: string[];
            /**
             * Horizon Days
             * @default 30
             */
            horizon_days: number;
            /**
             * Insight Language
             * @default vi
             */
            insight_language: string;
            /**
             * Insight Hour
             * @default 07:30
             */
            insight_hour: string;
            /**
             * Country Code
             * @default vn
             */
            country_code: string;
        };
        /** TenantOut */
        TenantOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /** Scan Times */
            scan_times: string[];
            /** Horizon Days */
            horizon_days: number;
            /** Insight Language */
            insight_language: string;
            /** Insight Hour */
            insight_hour: string;
            /** Country Code */
            country_code: string;
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TenantUpdate */
        TenantUpdate: {
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Scan Times */
            scan_times?: string[] | null;
            /** Horizon Days */
            horizon_days?: number | null;
            /** Insight Language */
            insight_language?: string | null;
            /** Insight Hour */
            insight_hour?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Active */
            active?: boolean | null;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Role */
            role: string;
            /** Tenant Id */
            tenant_id?: number | null;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Tenant Id */
            tenant_id: number | null;
            /** Active */
            active: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Role */
            role?: string | null;
            /** Active */
            active?: boolean | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchItemCreate */
        WatchItemCreate: {
            /** Booking Url */
            booking_url: string;
            /**
             * Role
             * @default competitor
             */
            role: string;
            /** Label */
            label?: string | null;
        };
        /** WatchItemOut */
        WatchItemOut: {
            hotel: components["schemas"]["HotelOut"];
            /** Role */
            role: string;
            /** Label */
            label: string | null;
            /** Active */
            active: boolean;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
        };
        /** WatchItemUpdate */
        WatchItemUpdate: {
            /** Role */
            role?: string | null;
            /** Label */
            label?: string | null;
            /** Active */
            active?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_tenants_tenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"][];
                };
            };
        };
    };
    create_tenant_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tenant_tenants__tenant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tenant_tenants__tenant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings__settings_get: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_settings_patch: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_watchlist_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_hotel_watchlist_post: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_watchlist__hotel_id__delete: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path: {
                hotel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_watchlist__hotel_id__patch: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path: {
                hotel_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_now_watchlist_scan_now_post: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_overview_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hotel_detail_hotels__hotel_id__get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                event_limit?: number;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path: {
                hotel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HotelDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    day_detail_hotels__hotel_id__dates__stay_date__get: {
        parameters: {
            query?: {
                history_days?: number;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path: {
                hotel_id: number;
                stay_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_events_get: {
        parameters: {
            query?: {
                hotel_id?: number | null;
                event_type?: string | null;
                stay_from?: string | null;
                stay_to?: string | null;
                observed_since?: string | null;
                limit?: number;
                offset?: number;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_insights_insights_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insight_insights__insight_id__get: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path: {
                insight_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_insight_insights_generate_post: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    template_pms_template_get: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mapping_pms_mapping_get: {
        parameters: {
            query?: {
                adapter?: string;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_mapping_pms_mapping_put: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_pms_preview_post: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_pms_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_file_pms_import_post: {
        parameters: {
            query?: {
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_file_pms_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PmsImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_imports_pms_imports_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PmsImportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    own_daily_pms_daily_get: {
        parameters: {
            query?: {
                hotel_id?: number | null;
                limit?: number;
                /** @description Operator: tenant cần xem */
                tenant_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnDailyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_health_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthSummaryOut"];
                };
            };
        };
    };
    runs_health_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sessions_health_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScrapeSessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_now_all_health_scan_now_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanRunOut"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
